### ISSUE TITLE
Магические числа в коде

### ISSUE THREAD

**Issue by anklimovets** [Savmex/test_task#10]
Магические числа в коде.
10, 0, 1, 100, 12.0 etc.

Объяснить, в чем здесь проблема.

**Comment by Savmex** [comment]
Пример проблемы:
Допустим у нас есть 3 объекта UIView в разных частях программы, и для view.height мы задаем значение таким образом: view.height = 100
Если далее мы захотим изменить размер каждой из view в программе, нам нужно будет заменять все 3 строки
Мы можем определить переменную let viewHeight  = 100
и присваивать значение таким образом: view.height = viewHeight
Тогда что бы изменить значение view.height в каждой части программы, мы можем изменить значение переменной viewHeight,это будет намного эффективней.

**Comment by anklimovets** [comment]
Задача перекрыта. 
Магические числа в коде:
- 75, 100,  4.0 и т.д.
необходимо устранить. И еще раз подумать и описать чем использование такого кода опасно.

**Comment by Savmex** [comment]
помимо удобства редактирования кода(при отсутствии магических чисел и наличии именованных констант для этих значений), так же программа становится более надежной,т.к допустить ошибку будет сложнее,и конечно же хорошие имена констант повышают удобочитаемость кода.

**Comment by anklimovets** [comment]
75, 100.

задача переоткрыта.
