### ISSUE TITLE
Магические строки в коде.

### ISSUE THREAD

**Issue by anklimovets** [Savmex/test_task#11]
Магические строки в коде.
"Error", "No results" , "searchResult" etc.

Объяснить, в чем здесь проблема

**Comment by Savmex** [comment]
Исправлено.
Проблема таких строк в неясности, к примеру если мы увидим вывод "Error" в консоли, будет непонятно какая ошибка и в какой части кода произошла, нам нужно выводить подробную информацию об ошибке.
"searchResult" является идентификатором ячейки tableView и она в данном случае является такой же проблемой как и "магическое число", если мы захотим сменить идентификатор ячейки, и у нас нет переменной для этого идентификатора, а он попросту является "магической строкой", нам придется изменять идентификаторы в каждой строке кода где они используются.

**Comment by anklimovets** [comment]
Задача переоткрыта.
Магические строки в коде "Search...", "Montserrat-Light" и тд.

**Comment by Savmex** [comment]
Исправлено.
