### ISSUE TITLE
Публичная видимость атрибутов класса ViewController.

### ISSUE THREAD

**Issue by anklimovets** [Savmex/test_task#12]
Публичная видимость атрибутов класса ViewController. Объяснить, в чем здесь проблема.

Определить интерфейс класса ViewController и обосновать видимость его свойств.

**Comment by Savmex** [comment]
Исправлено.

**Comment by anklimovets** [comment]
Необходимо объяснить в чем проблема и в чем проблема использования публичной видимости там, где в этом нет нужды.

Протокл ViewControllerProtocol изботочен - его необходимо удалить.

**Comment by Savmex** [comment]
В принципе публичная видимость атрибутов класса (в моем случае ViewController) раскрывает реализацию,нарушая при этом абстракцию,а абстракция дает ряд плюсов:
1)мы не вдаемся в подробности реализации работы класса,что упрощает работу с ним
2)нам легче будет вносить изменения в код и это не повлияет на другие части программы(т.к они в принципе не зависят от  реализации нашего класса)
3)ограничение видимости членов класса так же ограничивает область поиска ошибок
