### ISSUE TITLE
Проблемы класса ViewController.

### ISSUE THREAD

**Issue by anklimovets** [Savmex/test_task#14]
1. ViewController слишком громоздки для такой относительно маленькой задачи.
2. ViewController избыточен. Он делает то, что не должен делать.
3. Дать понятие ViewController для паттерну MVC и привести реализацию класса в соответсвии с этим понятием.

**Comment by Savmex** [comment]
ViewController отправляет команды полученные от пользователя в логику программы и наши View позже отображают результаты этой команды пользователя.

**Comment by anklimovets** [comment]
Вьюконтроллер выполняет работу позиционирования и UI-объектов для всплывающего сообщения.
