### ISSUE TITLE
Неудачная нумерация версий.

### ISSUE THREAD

**Issue by anklimovets** [Savmex/test_task#16]
Неудачная нумерация версий. 
Следующую версию указать как 1.2.0, и далее продолжать менять минорную версию приложения. 

В комментарии указать как называются первая, вторая и третья цифра номера версии.

**Comment by Savmex** [comment]
первое число - Major version - версия архитектуры проекта
второе число - Minor version - алгоритмические и косметические изменения
третье число - Release - небольшие алгоритмические и косметические изменения
