### ISSUE TITLE
Зафиксировать текущее состояние кода версией приложения "1.0.0" в проекте, в том числе тегом в репозитории. 

### ISSUE THREAD

**Issue by anklimovets** [Savmex/test_task#2]
Зафиксировать текущее состояние кода версией приложения "1.0.0" в проекте, в том числе тегом в репозитории.

**Comment by Savmex** [comment]
В Info.plist установил версию "#1.0.0", так же добавил отдельную ветку для измененного приложения и там указал тег версии через git tag.

**Comment by anklimovets** [comment]
Тэг в репозитории не установлен.

Результат выполнения команды "git tag":
```
qws-kan-mac:test_task klimovetsan$ git tag
qws-kan-mac:test_task klimovetsan$ 
```

**Comment by Savmex** [comment]
Исправил.
