### ISSUE TITLE
Кросс-ссылка между классами.

### ISSUE THREAD

**Issue by anklimovets** [Savmex/test_task#20]
DataSearchViewController знает о LabelView.
LabelView знает о DataSearchViewController.

Разобраться в чем здесь проблема.

Найти аналогичные ошибки и устранить их.

**Comment by Savmex** [comment]
Кросс-ссылка может помешать удалению объектов из памяти когда один из них не нужен.

**Comment by anklimovets** [comment]
Не только. Перекрестные ссылки между классами затрудняют разработку.
