### ISSUE TITLE
Неверное использование компонента таблицы.

### ISSUE THREAD

**Issue by anklimovets** [Savmex/test_task#4]
Таблица участвует в качестве контейнера для компонентов UI, которые не связаны со списочными данными.
Необходимо выделить компонент строки для поиска, а так же компонент кнопки поиска отдельно от таблицы.

**Comment by Savmex** [comment]
Исправлено, новая версия: v1.0.1.
Прогресс по книге "Совершенный код": глава 3, страница 57.
