### ISSUE TITLE
 Проблемы в readme.txt

### ISSUE THREAD

**Issue by anklimovets** [Savmex/test_task#5]
Проблемы в readme.txt:
 * не имеет видимой структуры.
 * повествование начинается с деталей, а не с главного
 * содержит лишнее (описание навигации и т.п.)

Должна быть следующая информация:
 * наименование проекта
 * краткое описание
 * системные требования

**Comment by Savmex** [comment]
Исправлено.

**Comment by anklimovets** [comment]
1. Отсутствует форматирование текста.
2. Убрать версию приложения.
3. Не указана минимальная поддерживаемая версия IOS.

**Comment by Savmex** [comment]
Исправлено.
