### ISSUE TITLE
 Избавиться от строковых аргументов, используемых для позиционирования.

### ISSUE THREAD

**Issue by anklimovets** [Savmex/test_task#6]
1.  Избавиться от строковых аргументов, используемых для позиционирования.

```
"H:|[v0]|"
"[v0(40)][v1(42)]-1-[v2(2)]-1-[v3]"
"H:|-70-[v0]-70-|"
```

2. Объяснить в комментариях к задаче, чем опаснен такой способо позиционирования элементов UI на экране.

**Comment by Savmex** [comment]
Опасность такого метода позиционирования в том, что, если мы допустим ошибку в  строке, в которой мы задаем расположение, то компилятор никак на это не отреагирует и не скажет об этой ошибке при билде,  и при запуске кода  мы можем получить ошибку времени выполнения.
