### ISSUE TITLE
 Отсутствует MVC. 

### ISSUE THREAD

**Issue by anklimovets** [Savmex/test_task#7]
Отсутсвует MVC. 
Вся логика реализована в ViewController.

**Comment by Savmex** [comment]
Перенес логику получения данных в отдельный объект специально созданного класса DataSearcher.

**Comment by anklimovets** [comment]
Объяснить как относится к Model.swift приложения структура HeightsAndOffsetsForSearchResultCell.

```
struct HeightsAndOffsetsForSearchResultCell{
     let topOffsetForTitleLabel = CGFloat(2)
     let horizontalOffsetForTitleLabel = CGFloat(2)
     let heightForTitleLabel = CGFloat(30)
     let topOffsetForLinkLabel = CGFloat(2)
     let horizontalOffsetForLinkLabel = CGFloat(3)
     let heightForLinkLabel = CGFloat(24)
}
```

Принять меры по ограничению ответственности  Model.swift.

**Comment by Savmex** [comment]
Исправлено, Model теперь хранит только структуры для задания кастомных типов данных.

**Comment by anklimovets** [comment]
Написать в комментарий этой задачи определение и  ответственность модели в соответсвии с паттерном MVC.

Выделить модель структурно, на уровне файловой системы.
Привести реализацию модели в соответсвии с определением и ответственностью.

**Comment by Savmex** [comment]
Model - контейнер для данных
Его ответственность - обеспечение доступа к данным и их изменение при обращении.

**Comment by anklimovets** [comment]
ResultsTableView хранит результаты поиска.
Ответить на вопрос где должны храниться результаты поиска?
Привести код в соответсвие с ответом.

**Comment by Savmex** [comment]
У нас имеется DataSearcher, он является слоем доступа к данным, значит храним данные в нем.
