### ISSUE TITLE
Непонятна ответственность Helper.swift

### ISSUE THREAD

**Issue by anklimovets** [Savmex/test_task#8]
1. Непонятна ответственность Helper.swift.

2. написать в комментариях к задаче ответ на вопрос "чем использование расширений класса (экстеншенов) может вредить проекту?".

**Comment by Savmex** [comment]
Исправлено, имя файла и содержимое изменено для лучшего понимания его ответственности.
Экстеншены опасны тем, что в какой-то мере они нарушают инкапсуляцию и могут ввести неясность в код проекта.
