### ISSUE TITLE
Код не документирован

### ISSUE THREAD

**Issue by anklimovets** [Savmex/test_task#9]
В проекте отсутствуют комментарии.
Подлежат обязательному документированию:

* классы и интерфейсы (протоколы)
* члены классов уровнем выше private
* хаки, трюки, обходные решения и пр. нетривиальные вещи

**Comment by Savmex** [comment]
Комментарии добавлены.

**Comment by anklimovets** [comment]
Код недостатоно документирован.
В дополнению к требованиям обязательного документирования, добавляется требования документирования структур и членов структур уровнем выше private.

**Comment by Savmex** [comment]
Исправлено.

**Comment by anklimovets** [comment]
Код не документирован в соответствии с гайдлайнами Apple. 
Необходимо: 
* ознакомиться с гадлайнами Apple
* предоставить (можно здесь в задаче) ссылку на официальный источник
* привести код в соответсвие с стандартами Apple

**Comment by Savmex** [comment]
Исправлено.
Ссылка на официальный источник:
https://developer.apple.com/library/archive/documentation/Xcode/Reference/xcode_markup_formatting_ref/index.html

**Comment by anklimovets** [comment]
В коде встречаются публичные методы классов без комментариев.

**Comment by anklimovets** [comment]
`Custom View for displaying LabelView from appropriate xib file.`

Неудачный комментарий.

**Comment by anklimovets** [comment]
Неудачное документирование классов практически по всем проекту.

Например класс.
ResultsTableView
```
/**
 Presents fetched results.
 */
```
Из документации не понятно что это за класс, какая у него ответственность, зачем он создавался в принципе.

Еще раз подчеркну - проверить в первую очередь комментарии классов по всему проекту. Если будет затруднено описать на английском- можете на русском, главное что бы была понятна суть комментария.

**Comment by anklimovets** [comment]
Плохое описание класса DataConverter.
` Includes methods for converting loaded data to needed type.`
Класс содержит методы для конвертации загруженных данных в нужный тип. 
1 - Ответственность этого класса "содержать методы" или просто конвертировать?
2 - Как класс определяет, что данные были именно загружены (это касается " загруженных данных")? Важно ли для этого класса каким образом были получены данные?
3 - Так и не понятно из какого типа в какой преобразуются данные?

Комментарии не должны вводить в заблуждение.
Проверить еще раз все комментарии классов.

**Comment by anklimovets** [comment]
Еще дополню по фразе "Includes methods". 
Это документирование семантики языка, ведь общеизвестно, что класс в себе включает методы и свойства.
